export {
	explainBlockingCut,
	isBlockingVerdict,
	MAX_BLOCKING_CUT_CANDIDATES,
	minimalBlockingCut,
} from "./claims/claim-blocking-cut.ts";
export { evaluateProofClosure } from "./claims/claim-closure.ts";
export {
	ClaimGraphError,
	canonicalClaimGraph,
	rootClaimIds,
	topologicalClaimOrder,
	validateClaimGraph,
} from "./claims/claim-graph.ts";
export {
	type BlockingCutExplanation,
	CLAIM_GRAPH_SCHEMA_VERSION,
	CLAIM_VERDICT_PRECEDENCE,
	type ClaimClosureEvaluation,
	type ClaimGraph,
	type ClaimNode,
	type ClaimNodeKind,
	type ClaimRule,
	type ClaimSeverity,
	type ClaimVerdict,
	OBSERVATION_TRUST_RANK,
	type ObservationNode,
	type ObservationPolarity,
	type ObservationSource,
	type ProofClosureInput,
	type ProofClosureResult,
	type VerificationVerdict,
	type WaiverNode,
	type WitnessIndependencePolicy,
	type WorkspaceCompleteness,
} from "./claims/claim-types.ts";
export { reduceRuntimeDecision } from "./decision.ts";
export { evaluateTask, ProtocolInvariantError } from "./evaluation.ts";
export type {
	AllCondition,
	AnyCondition,
	AttemptExecutor,
	AttemptOutcome,
	AttemptTrigger,
	ClaimCondition,
	ClaimEvaluation,
	ClaimPredicate,
	ClaimReasonCode,
	ClaimResult,
	EvaluationInput,
	EvaluationResult,
	ExecutionAttempt,
	JsonObject,
	JsonPrimitive,
	JsonValue,
	NotCondition,
	Observation,
	ObservationCondition,
	ProtocolVersion,
	RequirementLevel,
	RuntimeAction,
	RuntimeDecision,
	RuntimeDecisionInput,
	RuntimeDecisionPolicy,
	RuntimeDecisionReason,
	SemanticVerdict,
	TaskSpec,
	WaiverRecord,
} from "./types.ts";
export { PROTOCOL_VERSION } from "./types.ts";
export {
	ProtocolValidationError,
	parseEvaluationResult,
	parseExecutionAttempt,
	parseObservation,
	parseRuntimeDecision,
	parseTaskSpec,
	parseWaiverRecord,
} from "./validation.ts";
